// Code generated by llmango CLI. DO NOT EDIT.
package mango

import (
	"log"

	"github.com/llmang/llmango/llmango"
	"github.com/llmang/llmango/openrouter"
)

type Mango struct {
	*llmango.LLMangoManager
}

func CreateMango(or *openrouter.OpenRouter) (*Mango, error) {
	llmangoManager, err := llmango.CreateLLMangoManger(or)
	if err != nil {
		log.Fatalf("failed to setup llmango manager: %v", err)
	}

	// Initialize goals
	llmangoManager.AddGoals(
	)

	// Initialize prompts
	llmangoManager.AddPrompts(
	)

	return &Mango{llmangoManager}, nil
}

